### ISSUE TITLE
'knot' user creation fails when other users are created after

### ISSUE THREAD

**Issue by netoax** [CESARBR/knot-gateway-buildroot#3]
When a new package (redis) was added to the system, it has created a linux user with the same uid used for the "knot" user. This made some processes that executed as 'knot' user to fail.

### Setup

**Steps to reproduce**

1. Run `make menuconfig` and select a package that create a new user (e.g. redis);
2. Build the linux image;
3. flash the SD card.

**Expected result**

All KNoT processes must be running as "knot" user.

**Actual result**

The webui and knot-fog aren't being started. Besides, the knotd and nrfd processes are running as "redis" user.

**Possible solution**

Instead of using a fixed value for the "knot" uid, it should be defined dynamically.

**Comment by pauloserrafh** [comment]
@joaoaneto  
From what I've read on [BR manual, chapter 23](https://buildroot.org/downloads/manual/manual.html#makedev-syntax), perhaps we could set `uid` and `gid` on `knot/board/raspberrypi/device_table.txt` to either:
* -1 (if it follows the same convention of makeuser syntax and setting to -1 makes the BR automatically calculate)
* actual names for user and groups. I'd suggest: `knot-user` and `knot-group` to KNoT related package and `rabbitmq-user` and `rabbitmq-group`. 

IMO having the actual names is better, since if we need to use the user or group for anything, it will be necessary to always update when (if) adding new packages that create users.
Or is there any issue with this that you already have in mind? cc @alla3 @vitbaq @jcorde 

Will try to run some initial testing, but if you've already done that let me know (or if someone wants to do it/has time to do it).

**Comment by netoax** [comment]
I have built an image with the redis package and the reported issue apparently isn't occurring anymore.

```text
root:x:0:0:root:/root:/bin/sh
daemon:x:1:1:daemon:/usr/sbin:/bin/false
bin:x:2:2:bin:/bin:/bin/false
sys:x:3:3:sys:/dev:/bin/false
sync:x:4:100:sync:/bin:/bin/sync
mail:x:8:8:mail:/var/spool/mail:/bin/false
www-data:x:33:33:www-data:/var/www:/bin/false
operator:x:37:37:Operator:/var:/bin/false
nobody:x:65534:65534:nobody:/home:/bin/false
knot:x:1003:1003:"KNoT service user":/:/bin/sh
avahi:x:1000:1000::/:/bin/false
dbus:x:1001:1001:DBus messagebus user:/var/run/dbus:/bin/false
sshd:x:1002:1002:SSH drop priv user:/:/bin/false
postgres:x:1004:1004:PostgreSQL Server:/var/lib/pgsql:/bin/sh
rabbitmq:x:1005:1005:rabbitmq-server daemon:/var/lib/rabbitmq:/bin/sh
redis:x:1006:1006:Redis Server:/var/lib/redis:/bin/false
```
